# Generated by Django 3.0.5 on 2020-04-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=4)),
                ('path', models.CharField(max_length=200)),
                ('status_code', models.IntegerField(default=200)),
                ('response_time', models.IntegerField(default=0)),
                ('time_unit', models.CharField(max_length=2)),
            ],
        ),
    ]
